{
 "title": "Docker Swarm Services",
 "description": "Docker Swarm stacks and services metrics",
 "tags": [ "swarmprom" ],
 "time": { "from": "now-15m", "to": "now" },
 "refresh": "30s",
 "templating": {
  "list": [
   { "name": "node_id", "label": "Swarm Node", "query": "node_meta" },
   {
    "name": "interval",
    "label": "Interval",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   }
  ]
 },
 "panels": [
  { "title": "Overview", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Nodes",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 0, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_node_id =~\"$node_id\"}) by (container_label_com_docker_swarm_node_id))"
    }
   ]
  },
  {
   "title": "Stacks",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 2, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_stack_namespace=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\"}) by (container_label_com_docker_stack_namespace))"
    }
   ]
  },
  {
   "title": "Services",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 4, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(count(container_tasks_state{container_label_com_docker_swarm_service_name=~\".+\", container_label_com_docker_swarm_node_id=~\"$node_id\"}) by (container_label_com_docker_swarm_service_name))"
    }
   ]
  },
  {
   "title": "Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 6, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\"}[5m])) "
    }
   ]
  },
  {
   "title": "All Containers",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 2, "x": 8, "y": 1 },
   "format": "none",
   "valueName": "avg",
   "targets": [
    {
     "expr": "count(rate(container_last_seen[5m])) "
    }
   ]
  },
  {
   "title": "Health Checks",
   "type": "graph",
   "gridPos": { "h": 4, "w": 14, "x": 10, "y": 1 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(increase(engine_daemon_health_checks_total[$interval]) * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  ",
     "legendFormat": "checks"
    },
    {
     "expr": "sum(increase(engine_daemon_health_checks_failed_total[$interval]) * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  ",
     "legendFormat": "failed"
    }
   ]
  },
  {
   "title": "Available Memory",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 0, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_memory_MemAvailable / node_memory_MemTotal) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "Available Disk Space",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 4, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum((node_filesystem_free{mountpoint=\"/\"} / node_filesystem_size{mountpoint=\"/\"}) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
    }
   ]
  },
  {
   "title": "CPU Idle",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 8, "y": 5 },
   "format": "percent",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(irate(node_cpu{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) * 100 / count(node_cpu{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) "
    }
   ]
  },
  {
   "title": "Network Uploads",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 12, "y": 5 },
   "format": "KBs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) / 1024"
    }
   ]
  },
  {
   "title": "Network Downloads",
   "type": "singlestat",
   "gridPos": { "h": 7, "w": 4, "x": 16, "y": 5 },
   "format": "KBs",
   "valueName": "avg",
   "targets": [
    {
     "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) / 1024"
    }
   ]
  },
  {
   "title": "CPU",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 12 },
   "collapsed": true,
   "panels": [
    {
     "title": "CPU usage by Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 12 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[1m])) by (container_label_com_docker_swarm_service_name) * 100 ",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "CPU Idle",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 12 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum(irate(node_cpu{mode=\"idle\"}[$interval]) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) * 100 / count(node_cpu{mode=\"user\"} * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"}) "
      }
     ]
    },
    {
     "title": "CPU usage by Container (top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
     "yaxes": [
      { "format": "percent" }
     ],
     "targets": [
      {
       "expr": "topk(10, sum(irate(container_cpu_usage_seconds_total{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[$interval])) by (name)) * 100 ",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "RAM",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 13 },
   "collapsed": true,
   "panels": [
    {
     "title": "Memory usage by Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 20, "x": 0, "y": 13 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "sum(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
       "legendFormat": "Used {{container_label_com_docker_swarm_service_name}}"
      },
      {
       "expr": "sum(container_memory_cache{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}) by (container_label_com_docker_swarm_service_name) ",
       "legendFormat": "Cached {{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "Available Memory",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 20, "y": 13 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum((node_memory_MemAvailable / node_memory_MemTotal) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
      }
     ]
    },
    {
     "title": "Memory usage by Container (top 10)",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 20 },
     "yaxes": [
      { "format": "decbytes" }
     ],
     "targets": [
      {
       "expr": "topk(10, avg_over_time(container_memory_usage_bytes{container_label_com_docker_swarm_node_id=~\"$node_id\", id=~\"/docker/.*\"}[$interval]))",
       "legendFormat": "{{name}}"
      }
     ]
    }
   ]
  },
  {
   "title": "Disk",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 14 },
   "collapsed": true,
   "panels": [
    {
     "title": "Cluster IOPS",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 14 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(irate(container_fs_reads_total[$interval]) )",
       "legendFormat": "Reads"
      },
      {
       "expr": "sum(irate(container_fs_writes_total[$interval])) ",
       "legendFormat": "Writes "
      }
     ]
    },
    {
     "title": "Available Disk Space",
     "type": "singlestat",
     "gridPos": { "h": 7, "w": 4, "x": 10, "y": 14 },
     "format": "percent",
     "valueName": "avg",
     "targets": [
      {
       "expr": "sum((node_filesystem_free{mountpoint=\"/\"} / node_filesystem_size{mountpoint=\"/\"}) * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"} * 100) / count(node_meta * on(instance) group_left(node_name) node_meta{node_id=~\"$node_id\"})"
      }
     ]
    }
   ]
  },
  {
   "title": "Network",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 },
   "collapsed": true,
   "panels": [
    {
     "title": "Network received by Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "Network transmitted by Service",
     "type": "graph",
     "gridPos": { "h": 7, "w": 24, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_transmit_bytes_total{container_label_com_docker_swarm_node_id=~\"$node_id\"}[$interval])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{container_label_com_docker_swarm_service_name}}"
      }
     ]
    },
    {
     "title": "Cluster Network Traffic",
     "type": "graph",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 30 },
     "yaxes": [
      { "format": "Bps" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_network_receive_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "Received"
      },
      {
       "expr": "- sum(rate(container_network_transmit_bytes_total{id=\"/\"}[$interval])) by (id)",
       "legendFormat": "Transmited"
      }
     ]
    }
   ]
  },
  {
   "title": "Docker",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 16 },
   "collapsed": true,
   "panels": [
    {
     "title": "Service Tasks",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(rate(container_last_seen{container_label_com_docker_swarm_node_id=~\"$node_id\"}[5m])) by (container_label_com_docker_swarm_service_name)",
       "legendFormat": "{{ container_label_com_docker_swarm_service_name }}"
      }
     ]
    },
    {
     "title": "Docker Daemon Network Actions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 16 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(engine_daemon_network_actions_seconds_count * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  by (action)",
       "legendFormat": "{{action }}"
      }
     ]
    },
    {
     "title": "Docker Daemon Container Actions",
     "type": "graph",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 23 },
     "yaxes": [
      { "format": "short" }
     ],
     "targets": [
      {
       "expr": "sum(engine_daemon_container_actions_seconds_count * on(instance) group_left(node_id) swarm_node_info{node_id=~\"$node_id\"})  by (action)",
       "legendFormat": "{{action }}"
      }
     ]
    },
    {
     "title": "Docker Engine Info",
     "type": "table",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 23 },
     "targets": [
      {
       "expr": "sum(engine_daemon_engine_info * on(instance) group_left(node_id) swarm_node_info) by (kernel, os, graphdriver, version, node_id)"
      }
     ]
    }
   ]
  }
 ]
}